# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html

# This model initially had no columns defined. If you add columns to the
# model remove the '{}' from the fixture names and add the columns immediately
# below each fixture, per the syntax in the comments below

my_first_job:
  cron: "*/1 * * * *" #it will retrieve data every 1 minute
  class: "HardWorker"

my_second_job:
  cron: "30 12 * * *" #it will run every day at 12.30
  class: "PromoMailWorker"
